import { generateJob, generateRaafJob, type Channel, type Job, type JobPhase } from './jobgen.js';

type Send = (msg: unknown) => void;
type Point = { lat: number; lon: number; at: number; channel: Channel };

const TARGET_BY_CHANNEL: Record<Channel, number> = { emergency: 10, raafv: 6 };
const MAX_JOBS = 80;
const AVAILABLE_TTL_MS = 14 * 60_000; // an unclaimed job stands down after this
const COMPLETE_TTL_MS = 90_000; // drop finished jobs after this
const CLAIM_TTL_MS = 20 * 60_000; // reclaim jobs a dropped operator never started
const OPERATOR_TTL_MS = 12 * 60_000; // forget where an operator was after this

/**
 * Global tasking pool shared by every connected operator. Jobs are generated by
 * the server so people can browse and claim before loading a sim.
 */
export class JobHub {
  private jobs = new Map<string, Job>();
  private subs = new Set<Send>();
  /** where connected operators are, so new jobs land within reach */
  private operators = new Map<string, Point>();

  private gen(channel: Channel, near: { lat: number; lon: number } | null): Job {
    return channel === 'raafv' ? generateRaafJob(near) : generateJob(near);
  }

  /** An operator tells us their base / position (and which board they're on). */
  locate(clientId: string, lat: number, lon: number, channel: Channel = 'emergency'): void {
    if (!Number.isFinite(lat) || !Number.isFinite(lon)) return;
    const key = `${clientId}:${channel}`;
    const first = !this.operators.has(key);
    this.operators.set(key, { lat, lon, at: Date.now(), channel });
    // Give a newly-located operator an immediate in-range board.
    if (first || this.jobsWithinNm(lat, lon, 260, channel) < 4) {
      const want = Math.min(5, MAX_JOBS - this.jobs.size);
      for (let i = 0; i < want; i++) this.upsert(this.gen(channel, { lat, lon }));
    }
  }
  private jobsWithinNm(lat: number, lon: number, nm: number, channel: Channel): number {
    let n = 0;
    for (const j of this.jobs.values()) {
      if (j.status !== 'available' || (j.channel ?? 'emergency') !== channel) continue;
      const dLat = (j.lat - lat) * 60;
      const dLon = (j.lon - lon) * 60 * Math.cos((((lat + j.lat) / 2) * Math.PI) / 180);
      if (Math.hypot(dLat, dLon) <= nm) n++;
    }
    return n;
  }
  forget(clientId: string): void {
    for (const key of this.operators.keys()) if (key.startsWith(`${clientId}:`)) this.operators.delete(key);
  }
  private activeOperatorPoints(channel?: Channel): Point[] {
    const cut = Date.now() - OPERATOR_TTL_MS;
    const out: Point[] = [];
    for (const [id, p] of this.operators) {
      if (p.at < cut) this.operators.delete(id);
      else if (!channel || p.channel === channel) out.push(p);
    }
    return out;
  }

  subscribe(send: Send): () => void {
    this.subs.add(send);
    send({ type: 'job.list', jobs: [...this.jobs.values()] });
    return () => this.subs.delete(send);
  }

  private broadcast(msg: unknown): void {
    for (const s of this.subs) {
      try {
        s(msg);
      } catch {
        /* dropped socket */
      }
    }
  }

  private upsert(job: Job): void {
    this.jobs.set(job.id, job);
    this.broadcast({ type: 'job.upsert', job });
  }

  private remove(id: string): void {
    if (this.jobs.delete(id)) this.broadcast({ type: 'job.remove', id });
  }

  list(): Job[] {
    return [...this.jobs.values()];
  }

  stats() {
    let available = 0;
    let claimed = 0;
    let active = 0;
    let raafv = 0;
    for (const j of this.jobs.values()) {
      if ((j.channel ?? 'emergency') === 'raafv') raafv++;
      if (j.status === 'available') available++;
      else if (j.status === 'claimed') claimed++;
      else if (j.status === 'active') active++;
    }
    return { jobs: this.jobs.size, available, claimed, active, raafv };
  }

  // --- operator actions ------------------------------------------------

  private onParty(j: Job, clientId: string): boolean {
    return (j.party ?? []).some((p) => p.clientId === clientId);
  }

  claim(id: string, clientId: string, name: string): Job | { error: string } {
    const j = this.jobs.get(id);
    if (!j) return { error: 'Job no longer available.' };
    if (j.status !== 'available') {
      // Already being worked — treat a claim as a join so crews can share a call.
      return this.join(id, clientId, name);
    }
    j.status = 'claimed';
    j.claimedBy = clientId;
    j.claimedByName = name || 'Operator';
    j.claimedAt = Date.now();
    j.party = [{ clientId, name: name || 'Operator', joinedAt: Date.now() }];
    this.upsert(j);
    return j;
  }

  /** Add a unit to a call that another crew already holds. */
  join(id: string, clientId: string, name: string): Job | { error: string } {
    const j = this.jobs.get(id);
    if (!j) return { error: 'Job no longer available.' };
    if (j.status === 'available') return this.claim(id, clientId, name);
    if (j.status === 'complete') return { error: 'That call is finished.' };
    j.party = j.party ?? [];
    if (!this.onParty(j, clientId)) {
      j.party.push({ clientId, name: name || 'Operator', joinedAt: Date.now() });
      this.upsert(j);
    }
    return j;
  }

  /** Leave a call. If the last member leaves it goes back on the board. */
  leave(id: string, clientId: string): Job | { error: string } {
    const j = this.jobs.get(id);
    if (!j) return { error: 'Unknown job.' };
    j.party = (j.party ?? []).filter((p) => p.clientId !== clientId);
    if (j.party.length === 0) {
      j.status = 'available';
      j.claimedBy = null;
      j.claimedByName = null;
      j.claimedAt = null;
      j.phase = null;
    } else if (j.claimedBy === clientId) {
      // hand the lead to the next member still on the call
      j.claimedBy = j.party[0]!.clientId;
      j.claimedByName = j.party[0]!.name;
    }
    this.upsert(j);
    return j;
  }

  /** Back-compat alias — a "release" is just leaving the call. */
  release(id: string, clientId: string): Job | { error: string } {
    return this.leave(id, clientId);
  }

  start(id: string, clientId: string): Job | { error: string } {
    const j = this.jobs.get(id);
    if (!j) return { error: 'Unknown job.' };
    if (!this.onParty(j, clientId)) return { error: 'Claim or join the job first.' };
    j.status = 'active';
    if (!j.phase) j.phase = 'enroute';
    j.claimedAt = Date.now();
    this.upsert(j);
    return j;
  }

  progress(id: string, clientId: string, phase: JobPhase): Job | { error: string } {
    const j = this.jobs.get(id);
    if (!j) return { error: 'Unknown job.' };
    if (!this.onParty(j, clientId)) return { error: 'Not on this call.' };
    j.phase = phase;
    j.status = 'active';
    this.upsert(j);
    return j;
  }

  complete(id: string, clientId: string): void {
    const j = this.jobs.get(id);
    if (!j || !this.onParty(j, clientId)) return;
    j.status = 'complete';
    j.phase = 'returning';
    this.upsert(j);
    setTimeout(() => this.remove(id), COMPLETE_TTL_MS).unref?.();
  }

  /** Called when a socket closes — drop the operator from any call they hadn't started. */
  releaseAllClaims(clientId: string): void {
    for (const j of this.jobs.values()) {
      if (j.status === 'claimed' && this.onParty(j, clientId)) this.leave(j.id, clientId);
    }
  }

  // --- generation + housekeeping -------------------------------------

  tick(): void {
    const now = Date.now();
    for (const j of [...this.jobs.values()]) {
      if (j.status === 'complete' && now - j.createdAt > COMPLETE_TTL_MS + 5_000) this.remove(j.id);
      else if (j.status === 'available' && now - j.createdAt > AVAILABLE_TTL_MS) this.remove(j.id);
      else if (j.status === 'claimed' && j.claimedAt && now - j.claimedAt > CLAIM_TTL_MS) this.release(j.id, j.claimedBy!);
    }

    for (const channel of ['emergency', 'raafv'] as Channel[]) {
      const available = [...this.jobs.values()].filter(
        (j) => j.status === 'available' && (j.channel ?? 'emergency') === channel,
      ).length;
      const target = TARGET_BY_CHANNEL[channel];
      if (available >= target || this.jobs.size >= MAX_JOBS) continue;
      const add = Math.min(3, target - available);
      const points = this.activeOperatorPoints(channel);
      for (let i = 0; i < add; i++) {
        const near = points.length && Math.random() < 0.9 ? points[Math.floor(Math.random() * points.length)]! : null;
        this.upsert(this.gen(channel, near));
      }
    }
  }

  /** Seed the pool so the first operator to connect sees a full board. */
  seed(): void {
    for (const channel of ['emergency', 'raafv'] as Channel[])
      for (let i = 0; i < TARGET_BY_CHANNEL[channel]; i++) this.upsert(this.gen(channel, null));
  }
}

export const jobHub = new JobHub();
